name: Kindle Unlimited Check

on:
  schedule:
    - cron: '0 0 * * *'  # 毎日9:00 JST（0:00 UTC）
  workflow_dispatch:

jobs:
  run-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run script
        run: python main.py
        env:
          YOUR_LINE_NOTIFY_TOKEN: ${{ secrets.LINE_NOTIFY_TOKEN }}
